version: "3.8"

services:
  front-app:
    image: dendriel/npc-data-manager-front:latest
    command: "node server.js"
    ports:
      - 80:80
    working_dir: /app
    restart: always
    environment:
      - FRONTEND_PORT=80
      - BACKEND_URL=http://10.10.10.5:8080/rest/
      - STORAGE_URL=http://10.10.10.5:8081/storage/
